version: '3.8'

services:
  app:
    build: .
    container_name: super_ia_app
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_NAME=corporat_base_super_ia
      - DB_USER=corporat_coac_user
      - DB_PASS=*6LuhePgy=9?Zy-&
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: super_ia_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: corporat_base_super_ia
      MYSQL_USER: corporat_coac_user
      MYSQL_PASSWORD: '*6LuhePgy=9?Zy-&'
      MYSQL_ROOT_PASSWORD: rootpassword123
    volumes:
      - db_data:/var/lib/mysql
      - ./super_ia_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db_data:
